export { ReactComponent as RightArrow } from './right-arrow.svg'
export { ReactComponent as LeftArrow } from './left-arrow.svg'

export { ReactComponent as Books } from './books.svg'
export { ReactComponent as Bubbles } from './bubbles.svg'
export { ReactComponent as Hand } from './hand.svg'
export { ReactComponent as Plan } from './plan.svg'
export { ReactComponent as Roulette } from './roulette.svg'
export { ReactComponent as SewingMachine } from './sewing-machine.svg'
export { ReactComponent as Window } from './window.svg'