export const staticUrls = {
  "/interiors": "Интерьеры",
  "/interiors/plan-1": "Квартира в Екатеринбурге",
  "/interiors/blueprint-1": "Чертеж: квартира в Екатеринубрге",
  "/interiors/plan-2": "Офис в Екатеринбурге,145 кв.м",
  "/interiors/blueprint-2": "Чертеж: офис в Екатеринбурге,145 кв.м",
  "/interiors/plan-3": "Дом в Сочи,367 кв.м",
  "/interiors/blueprint-3": "Чертеж: дом в Сочи,367 кв.м",
  "/interiors/plan-4": "Квартира в Екатеринбурге, 90 кв.м",
  "/interiors/blueprint-4": "Чертеж: квартира в Екатеринбурге, 90 кв.м",
  "/questionnaire": "Анкета",
  "/services/interior-decoration": "Дизайн интерьеров",
  "/services/interior-decoration/material": "Материалы",
  "/services": "Услуги",
  "/material-name": "Бренды",
  "/decor": "Декор",
  "/contact": "Контакты",
  "/services/interior-design": "Дизайн интерьеров",
  "/services/furniture-manufacturing": "Изготовление мебели",
  "/decoration": "Декорирование",
  "/room": "Комнаты",
  "/custom-furniture": "Мебель на заказ",
};
